app:
  name: "校园失物招领"
  homeSubtitle: "找回每一件重要的小物"
  loginSubtitle: "登录校园失物招领"
  registerSubtitle: "加入校园失物招领"
#修改IP地址请到/common/config.js或使用set-server-ip.js
api:
  baseUrl: "http://localhost:3000"
  prefix: "/api"
  uploadPath: "/upload"

publish:
  maxImages: 3

